{% set name = "sha256" %}
{% set version = "0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/cloudtools/sha256/archive/{{ version }}.tar.gz
  sha256: f07d40006ad22b0d38acefff25ed1337993688eb87328b03c3aaaf39ded03a05

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 3

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - cython
    - pip
    - python
  run:
    - python

test:
  imports:
    - sha256
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/sha256/
  summary: sha256 library with midstate
  dev_url: https://github.com/cloudtools/sha256
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
